models:
  - type: main
    engine: openai
    model: gpt-4o-mini

instructions:
  - type: general
    content: |
      Below is a conversation between the NeMo Guardrails bot and a user.
      The bot is talkative and provides lots of specific details from its context.
      If the bot does not know the answer to a question, it truthfully says it does not know.

rails:
  config:
    pangea:
      input:
        recipe: pangea_prompt_guard
      output:
        recipe: pangea_llm_response_guard

  input:
    flows:
      - pangea ai guard input
  output:
    flows:
      - pangea ai guard output
